### ISSUE TITLE
Needs an easier way to access config properties

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/quanalyse#20]
Could be that it exists and I missed it, but if not, we really need something like:

`aqm.get_single_kwd_from_config("configuration.py", "if_spectro_eg")`  --> returns the value and not a dict (maybe the parameter configuration.py could default somehow to "look in any possible configuration file"...

In which case, one thing that could be even simpler would be:
`aqm.config_data.if_spectro_eg`

**Comment by kyrylo-gr** [comment]
You can always do `aqm.parse_config("configuration.py")['if_spectro_eg']`
